name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/
    - name: Build
      run: dotnet build ./src/ --no-restore
    - name: Run docker-compose
      uses: sudo-bot/action-docker-compose@latest
      with: 
        cli-args: "up -d"
    - name: Test
      run: dotnet test ./src/ --no-build --verbosity normal
    - name: Shutdown docker-compose
      uses: sudo-bot/action-docker-compose@latest
      with: 
        cli-args: "down"

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x    
    - name: Build
      run: dotnet pack --configuration Release ./src/
    - name: Publish
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json
